config/routes.rb
Tricoachapp::Application.routes.draw do
  resource :session

  resources :users

  resources :races 
  
	root   "athletes#index"
  	resources :athletes do
  		resources :raceregs
  	end

  	get 'signup' => 'users#new'

  	

end

app/models/race.rb
class Race < ActiveRecord::Base
	has_many :raceregs, dependent: :destroy
	has_many :participants, through: :raceregs, source: :user
	
	validates :name, :race_date, :priority, presence:true


end

app/controllers/races_controller.rb
class RacesController < ApplicationController

	def index

		@races = Race.all
	end


	def show
		
		@race = Race.find(params[:id])
	end

	def edit
		@race = Race.find(params[:id])
	end

end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @race.name %></h1>
</header>

<%= render 'form' %>

app/views/races/index.html.erb
<h1 id="content-header">
	<%= pluralize(@races.size, 'Race') %>
</h1>
  

<ul>
	<% @races.each do |race| %>
 	 	<li><%= link_to race.name, race %> </li>
 	<% end %>

  
</ul>

app/views/races/show.html.erb
<article>
  <header>
    <h1><%= @race.name %></h1>
  </header>
  <h2>Description</h2>
    <p>
      <%= @race.description %>
    </p>

<h3>Race date</h3>
  <p>
    <%= @race.race_date %>
  </p>


<h3>Swim Distance</h3>
  <p>
    <%= @race.swim_distance %>
  </p>

<h3>Bike Distance</h3>
  <p>
    <%= @race.bike_distance %>
  </p>

<h3>Run Distance</h3>
  <p>
    <%= @race.run_distance %>
  </p>


<!--<h3>Image url</h3>
  <p> 
    <%= @race.image_url %>
  </p>
 -->
  
<h3>Race url</h3>
  <p>
    <%= @race.race_url %>
  </p>

<h3>Category</h3>
  <p>  
    <%= @race.race_category %>
  </p>




<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>

</article>