config/routes.rb
Tricoachapp::Application.routes.draw do
  resource :session

  resources :users

  resources :races 
  
	root   "athletes#index"
  	resources :athletes do
  		resources :raceregs
  	end

  	get 'signup' => 'users#new'

  	

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base

	

#	validates :first_name, :last_name,  presence: true

#	validates :image_file_name, allow_blank: true, format: {
#  with:    /\w+.(gif|jpg|png)\z/i,
#  message: "must reference a GIF, JPG, or PNG image"
# }

	def self.under_thirty
		where("birthdate >= ?", 30.years.ago).order("last_name desc")
	end


	def age
  		age = Date.today.year - birthdate.year
  		age -= 1 if birthdate.strftime("%m%d").to_i > Date.today.strftime("%m%d").to_i
  		age
	end




	def previous_races
		raceregs.where( "date <?", Time.now).order("date asc")
	end

	def upcoming_races
		raceregs.where( "date >=?", Time.now).order("date asc")
	end

	def next_race
		upcoming_races.first
#		next_race = raceregs.order('date asc').first
	end

end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
	before_action :require_signin, except: [:index, :show]
	before_action :require_admin, except: [:index, :show]


	def index
#		@athletes=Athlete.all()
#		@athletes=Athlete.under_thirty
#		@athletes=Athlete.order('last_name')
		@athletes=User.where(athlete: true).order('last_name')
	end

	def show
		#@athlete=Athlete.find(params[:id])
		@athletes=User.where(athlete: true).find(params[:id])
	end

	def edit
		@athlete=Athlete.find(params[:id])
	end


	def update
		@athlete=Athlete.find(params[:id])
	  	if @athlete.update(athlete_params)
	  		flash[:notice]
	  		redirect_to @athlete, notice: "Athlete succesfully updated!" 
	  	else
	  		render :edit
	  	end

	end

	def new
		@athlete = Athlete.new
	end

	def create
	  	@athlete = Athlete.new(athlete_params)	
		if @athlete.save
			flash[:notice]
	  		redirect_to @athlete, notice: "Athlete succesfully created!" 
		else
			render :new
		end
	end


	def destroy
		@athlete = Athlete.find (params[:id])
		@athlete.destroy
		redirect_to athletes_url, alert: "Athlete successfully deleted!"

	end



private

	def athlete_params
		athlete_params = params.require(:athlete).
	  			permit(:first_name, :last_name, :birthdate, :address_one, :address_two, :city, :state, :zip, :image_file_name)
	end




end

app/helpers/athletes_helper.rb
module AthletesHelper

def image_for(athlete)
  if athlete.image_file_name.blank?
    image_tag('placeholder.png')
  else
    image_tag(athlete.image_file_name)
  end
end

 def format_next_race(athlete)
   if athlete.next_race.count>0
     athlete.next_race.name
   else
    content_tag(:p, "No Races Scheduled")
   end
 end

#def format_previous_races(athlete)
#	if athlete.previous_races.any?
#	 	athlete.previous_races.each do |r|  
#			r.name
#		end
#	else
#		content_tag(:p, "No Prior Races")
#	end
#end

def delete_racereg_image
   image_tag('png/33.png', style: 'border: 0', :title => 'Delete Racereg')
 end

def edit_racereg_image
   image_tag('png/69.png', style: 'border: 0', :title => 'Edit Racereg')
end



end

app/views/athletes/_form.html.erb
<%= form_for(@athlete)  do |f| %>
  <%= render "shared/errors", object: @athlete %>
	<fieldset>
		<ol>
	<li class="required">	
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name,  autofocus: true %>

	</li>
	<li class="required">
		<%= f.label :last_name %><br/>
		<%= f.text_field :last_name %><br/>
	</li>
	<li class="required">
		<%= f.label :address_one %><br/>
		<%= f.text_field :address_one %><br/>
	</li>
	<li class="required">
		<%= f.label :address_two %><br/>
		<%= f.text_field :address_two %><br/>
	</li>
	<li class="required">
		<%= f.label :city %><br/>
		<%= f.text_field :city %><br/>
	</li>
	<li class="required">
		<%= f.label :state %><br/>
		<%= f.text_field :state %><br/>
	</li>
	<li class="required">
		<%= f.label :zip %><br/>
		<%= f.text_field :zip %><br/>
	</li>
	<li class="required">
		<%= f.label :birthdate %><br/>
		<%= f.date_select :birthdate, start_year: 1915 %><br/>
	</li>

	<li class="required">
  		<%= f.label :image_file_name %><br/>
  		<%= f.text_field :image_file_name %>
	</li>
	</ol>

	<p>
		<%= f.submit %>
		<%= link_to "Cancel", athletes_path, class: 'button' %>
	</p>
	</fieldset>
<% end %>

app/views/athletes/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @athlete.first_name %></h1>
</header>

<%= render 'form' %>

app/views/athletes/index.html.erb
<ul id="athletes">
	<% @athletes.each do |athlete| %>
<li>
	<article class="athlete" id="<%= dom_id(athlete) %>">
	<header>
		<h2><%= link_to athlete.name, athlete %></h2>
			<%= image_for(athlete) %>
	</header>

	
	<table>
		<tr>
			<th>Birthdate</th>
			<td><%= athlete.birthdate %></td>
		</tr>
		<tr>
			<th>Location</th>
			<td><%= athlete.city %>, <%= athlete.state %></td>
		</tr>
	</table>
	</article>
</li>
<% end %>
</ul>

app/views/athletes/new.html.erb
<header id="content-header">
<h1>Add New Athlete</h1>
</header>

<%= render 'form' %> 

app/views/athletes/show.html.erb
<article id="athlete" class="athlete">
	<header>
		<%= image_for(@athlete) %>
		<h2><%= @athlete.first_name %> <%= @athlete.last_name %></h2>
	</header>


	<h3>Birthdate:</h3>
	<p>
		<%= @athlete.birthdate %>
	</p>

	<h3>Age</h3>
	<p>
		<%= @athlete.age %>
	</p>

	<h3>Address </h3>
	<p>
		<%= @athlete.address_one %><br />
		<%= @athlete.address_two %><br />
		<%= @athlete.city %>, 
		<%= @athlete.state %><br/>
		<%= @athlete.zip %>
	</p>

	<h3>Previous Races</h3>
		 <% if @athlete.previous_races.any? %>

			<% @athlete.previous_races.each do |r|  %>
				<p><%= r.name %>, <%= r.date %></p>
    		<% end %>

    	<% else %>
    		<p>No Previous Races</p>
    	<% end %>


	<h3>Upcoming Races</h3>
		 <% if @athlete.upcoming_races.any? %>

			<% @athlete.upcoming_races.each do |r|  %>
				<p><%= r.date %>:  <%= r.name %> </p>
    		<% end %>

    	<% else %>
    		<p>No Upcoming Races</p>
    	<% end %>

<!--
	<h3>Next Race</h3>
	<%#= format_next_race(@athlete) %>
-->


<footer>

	<%= link_to pluralize(@athlete.raceregs.size, "race registration"), athlete_raceregs_path(@athlete), class: 'button' %>
	<%= link_to "Add a Race", new_athlete_racereg_path(@athlete), class: 'button ok review'  %>

	
<nav>
	<% if current_user_admin? %>
	<%= link_to "Edit", edit_athlete_path(@athlete), class: 'button' %> | 
	<%= link_to "Delete", @athlete, 
				class: 'button', 
				method: :delete, data: {confirm: 'Are you sure?'} %> 
	<% end %>
</nav>

</footer>

</article>