config/routes.rb
Tricoachapp::Application.routes.draw do
  resource :session

  resources :users

  resources :races 
  
	root   "athletes#index"
  	resources :athletes do
  		resources :raceregs
  	end

  	get 'signup' => 'users#new'

  	

end

app/models/racereg.rb
class Racereg < ActiveRecord::Base
  belongs_to :user
  belongs_to :race


  validates :priority, presence:true

  PRIORITIES = ["A", "B", "C"]

  validates :priority, inclusion: {
  	in: PRIORITIES,
  	message:  "Must have priority A, B or C"
  }



  	


end

app/controllers/raceregs_controller.rb
class RaceregsController < ApplicationController
	before_action  :set_athlete

	def index
		@raceregs = @athlete.raceregs
	end

	def new
		@racereg = @athlete.raceregs.new
	end

	def show
	end

	def create
		@racereg = @athlete.raceregs.new (racereg_params)
		if @racereg.save
			flash[:notice]
	  		redirect_to athlete_raceregs_path(@athlete), 
	  		notice: "Racereg succesfully created!" 
		else
			render :new
		end
	end

	def destroy
		@racereg = @athlete.raceregs.find(params[:id])
		@racereg.destroy
		redirect_to athlete_raceregs_path(@athlete), alert: "Racereg successfully deleted!"
	end	


private
	def racereg_params
		params.require(:racereg).permit(:name, :date, :priority, :comment)
	end

private
	def set_athlete
		@athlete=Athlete.find(params[:athlete_id])
	end


end

app/helpers/raceregs_helper.rb
module RaceregsHelper



end

app/views/raceregs/index.html.erb
<article>
<header><h1><%= pluralize(@athlete.raceregs.size, "race registration") %> for <%= link_to(@athlete.first_name, @athlete) %> <%= link_to(@athlete.last_name, @athlete) %></h1>
</header>



<table class = "wide">
<thead>
	<th scope="col">Name</th>
	<th scope="col">Priority</th>
	<th scope="col">Date</th>
	<th scope="col">Comment</th>
	<th scope="col">Edit</th>
	<th scope="col">Delete</th>
</thead>
	<%   @raceregs.each do |racereg| %>
		<tr>
		<td class= "raceregs">
			
			<%= racereg.name %>
		</td>
		<td class = "priority">

			  <%=racereg.priority %> 
			
		</td>
		<td class= "date">
			
		 <%= racereg.date %>
		
		</td>
		<td class= "comment">
		
		 <%= racereg.comment %>
		
		</td>
		<td>
			<%= link_to edit_racereg_image, [@athlete, racereg] %>
		</td>
		<td>
			<%= link_to delete_racereg_image, [@athlete, racereg], 
				id: "#{dom_id(racereg)}_delete",
				method: :delete, 
				data: {confirm: 'Are you sure you want to delete this Race Registration?'} %> 
		</td>
		</tr>

	<% end %>
</table>

<footer>
	<nav>

	<%= link_to "Add a Race", new_athlete_racereg_path(@athlete), class: 'button ok review'  %> | 
	<%= link_to "Show Athlete", athlete_path(@athlete), class: 'button review' %> 
	
</nav>

</footer>
</article> 

app/views/raceregs/new.html.erb
<header id="content header">
	<h1>Add a Race Registration for <%= link_to(@athlete.first_name, @athlete) %></h1>
</header>

<%= form_for([@athlete, @racereg]) do |f| %>
  <%= render "shared/errors", object: @racereg %>

<fieldset>
	<ol>
		<li class="required">	
			<%= f.label :name %><br />
			<%= f.text_field :name,  autofocus: true %>
		</li>
		<li class = "required">
			<%= f.label :date %><br />
			<%= f.date_select :date %>
		</li>
		<li class = "required stars">
			<%= f.label :priority %><br />
			<%= f.select :priority, Racereg::PRIORITIES, prompt: "Pick One" %>
		</li>
		<li class = "required">
			<%= f.label :comment %><br />
			<%= f.text_field :comment %>
		</li>

		<li class = "required">
			<%= f.submit %>
		</li>
	</ol>
</fieldset>
<% end %>