config/routes.rb
Tricoachapp::Application.routes.draw do
  resource :session

  resources :users

  resources :races 
  
	root   "athletes#index"
  	resources :athletes do
  		resources :raceregs
  	end

  	get 'signup' => 'users#new'

  	

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2014
    <%= link_to 'Steel City Endurance, LTD','http://steelcityendurance.com' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
	<div id="masthead">
    	<h1><%= link_to 'Triathlon Coaching App', root_path %></h1>
    	<nav>
  <p>
  	<% if current_user %>
	  	<%= link_to current_user.name, current_user %> | 

	  	<%= link_to "Account Settings", edit_user_path(current_user) %> |
	  	<%= link_to "Sign Out", session_path, method: :delete, class: 'button' %>
	<% else %> 	
	    <%= link_to 'Sign Up', signup_path, class: 'button' %>
	    <%= link_to 'Sign In', new_session_path, class: 'button' %>
  	<% end %>
  </p> 
  	</div>


</nav>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
		<nav>
			<ul>
				<li class="all-athletes">
					<%= link_to 'All Athletes', athletes_path, class: 'button' %>
				</li>
				<% if current_user_admin? %>
				<li class="create-athlete">
					<%= link_to 'Add New Athlete', new_athlete_path, class: 'button' %>
				</li>	
				<% end %>
			</ul>
		</nav>
	</aside>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Triathlon Coaching App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">
	<%= render "layouts/flashes" %>

	<div id="container">
		<%= render "layouts/sidebar" %>	
		<section id="content">

			<%= yield %>
		</section>
	</div>
</div>

<%= render "layouts/footer" %>

</body>
</html>